-- Two strangers who sent /start to the staff bot and stopped there. The bot
-- creates a users row before it knows who you are, so each left a row and an
-- offer to open the manager; neither ever joined a group, created one, or was
-- invited, so nothing references them. One arrived in April, before the public
-- site existed; the other in July, when the site's "בטלגרם" hero button still
-- pointed customers at the bot. That button is gone as of this deploy.
--
-- The cleanup ran in production on deploy. The two Telegram IDs it matched on
-- have since been removed from this public repo, so the statement below is a
-- no-op: on any other database those rows never existed in the first place.
SELECT 1;
